version: "3.1"
services:
  db:
    #? Set container name
    container_name: book_db
    image: mongo:7.0.2

    #? Restart if down
    restart: always

    #? Environment
    environment:
      MONGO_INITDB_ROOT_USERNAME : "admin"
      MONGO_INITDB_ROOT_PASSWORD : "admin123"
      MONGO_INITDB_DATABASE : "book_db"

    #? Ports
    ports:
      - 27017:27017